package org.borland.ui;

import org.borland.core.EngineCore;

import javax.swing.*;
import java.awt.*;

public class Main {
    public static Main mainInstance;
    private EngineCore world;

    private JPanel mainPanel;
    private JButton button1;
    private JPanel worldRenderPanel;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Physical engine");
        mainInstance = new Main();
        frame.setContentPane(mainInstance.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();

        frame.setMinimumSize(new Dimension(640, 480));
        frame.setVisible(true);
    }

    public Main() {
        world = new EngineCore();

        WorldRenderMain worldRenderer = new WorldRenderMain(world);
        worldRenderPanel.add(worldRenderer.getWorldCanvas().getCanvas());
    }

    public EngineCore getWorld() {
        return world;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        worldRenderPanel = new JPanel();
        worldRenderPanel.setLayout(new BorderLayout(0, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(worldRenderPanel, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(button1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
